const DEFAULT_PRODUCTION_URL = "https://www.researchmatch.site";

function normalizedHttpOrigin(value: string | undefined): string | null {
  if (!value) return null;
  try {
    const url = new URL(value.startsWith("http") ? value : `https://${value}`);
    if (url.protocol !== "http:" && url.protocol !== "https:") return null;
    return url.origin;
  } catch {
    return null;
  }
}

/** Canonical origin for redirects generated by trusted server code. */
export function siteOrigin(): string {
  return (
    normalizedHttpOrigin(process.env.NEXT_PUBLIC_SITE_URL) ??
    normalizedHttpOrigin(process.env.VERCEL_PROJECT_PRODUCTION_URL) ??
    (process.env.NODE_ENV === "development" ? "http://localhost:3000" : DEFAULT_PRODUCTION_URL)
  );
}
